language: python
python:
  - 2.7
  - 3.8
env:
  - FILENAME=test-eslint1
  - FILENAME=test-eslint2
  - FILENAME=test-eslint3
  - FILENAME=test
  - FILENAME=test2
  - FILENAME=test3
install: pip install flake8 junit-xml pypistats yamlish
before_script: flake8 . --max-line-length=88
script:
  - python tap2junit/tap13.py
  - python -m tap2junit -i test/fixtures/${FILENAME}.tap -o test/output/${FILENAME}.xml
  - cat test/output/${FILENAME}.xml
  - pypistats recent tap2junit
  - pypistats python_major tap2junit --last-month
  - pypistats python_minor tap2junit --last-month
